"""
PDF Form Exporter for SchemeSaathi using ReportLab.
Generates an official-looking Indian Government Application PDF.
"""
import io
from typing import Dict, Any
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

def generate_application_pdf(filled_form: Dict[str, Any], user_profile: Dict[str, Any], app_id: str = "APP-2026-DEMO-10001") -> bytes:
    """Generates print-ready official application form PDF bytes."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=18,
        leading=22,
        textColor=colors.HexColor("#0B3D3F"),
        alignment=1
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#028090"),
        alignment=1
    )

    section_style = ParagraphStyle(
        'SectionHead',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#0B3D3F"),
        spaceBefore=10,
        spaceAfter=6
    )

    normal_style = styles['Normal']

    story = []

    # Header
    story.append(Paragraph("GOVERNMENT OF INDIA — WELFARE SCHEME APPLICATION FORM", title_style))
    story.append(Paragraph("Generated by SchemeSaathi Autonomous Personal Assistant", subtitle_style))
    story.append(Spacer(1, 12))

    # Reference Bar Table
    scheme_name = filled_form.get("scheme_name", "Welfare Scheme")
    ref_data = [
        [Paragraph(f"<b>Application Ref ID:</b> {app_id}", normal_style), Paragraph(f"<b>Scheme:</b> {scheme_name}", normal_style)],
        [Paragraph(f"<b>Status:</b> Pre-filled & Verified", normal_style), Paragraph(f"<b>Submission Date:</b> 2026-07-25", normal_style)]
    ]
    ref_table = Table(ref_data, colWidths=[270, 270])
    ref_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#F4F9F8")),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#028090")),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#CCCCCC")),
        ('PADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(ref_table)
    story.append(Spacer(1, 14))

    # Applicant Profile Details Table
    story.append(Paragraph("1. APPLICANT PERSONAL & FINANCIAL DETAILS", section_style))
    
    filled = filled_form.get("filled_fields", {})
    table_rows = [["Form Field", "Auto-Filled Value", "Status"]]
    
    for f_key, meta in filled.items():
        lbl = meta.get("label", f_key)
        val = str(meta.get("value", "N/A"))
        stat = meta.get("status", "Auto-filled")
        table_rows.append([lbl, val, stat])

    form_table = Table(table_rows, colWidths=[200, 240, 100])
    form_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#0B3D3F")),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0,0), (-1,0), 6),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#DDDDDD")),
        ('PADDING', (0,0), (-1,-1), 5),
    ]))
    story.append(form_table)
    story.append(Spacer(1, 14))

    # Declaration & Signature Block
    story.append(Paragraph("2. APPLICANT DECLARATION & SIGNATURE", section_style))
    dec_text = (
        "I hereby declare that all information provided above is true and complete to the best of my knowledge. "
        "I understand that any misrepresentation may lead to cancellation of benefits under the welfare scheme."
    )
    story.append(Paragraph(dec_text, normal_style))
    story.append(Spacer(1, 24))

    sig_data = [
        [Paragraph(f"<b>Applicant Name:</b> {user_profile.get('name', 'Citizen')}", normal_style), Paragraph("<b>Signature / Thumb Impression:</b>", normal_style)],
        [Paragraph("<b>Date:</b> 2026-07-25", normal_style), Paragraph("___________________________", normal_style)]
    ]
    sig_table = Table(sig_data, colWidths=[270, 270])
    sig_table.setStyle(TableStyle([
        ('PADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(sig_table)

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()

if __name__ == "__main__":
    test_form = {
        "scheme_name": "PM-KISAN",
        "filled_fields": {
            "applicant_name": {"label": "Applicant Full Name", "value": "Ramesh Kumar", "status": "Auto-filled"},
            "age": {"label": "Age", "value": "35", "status": "Auto-filled"},
            "income_lpa": {"label": "Annual Income", "value": "1.5 Lakhs", "status": "Auto-filled"}
        }
    }
    pdf_bytes = generate_application_pdf(test_form, {"name": "Ramesh Kumar"})
    print(f"Generated PDF bytes length: {len(pdf_bytes)}")
